# Generated by Django 5.1.7 on 2025-04-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_channelmedia_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmedia',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_media', to='chat.channelcategory'),
        ),
    ]
