# Generated by Django 5.1.7 on 2025-04-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_channelmedia_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmedia',
            name='category',
        ),
        migrations.CreateModel(
            name='CategoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/icons')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/banners')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.channelcategory')),
            ],
        ),
    ]
