# Generated by Django 5.1.7 on 2025-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_channelmedia_category_categorymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymedia',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='categorymedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
